application:
  name: animais-perdidos-api
  project: animais-perdidos-api
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql-3498225
- type: MongoDB
  version: "4.4"
  name: my-MongoDB-3498225
- type: REDIS
  version: "6.0"
  name: my-redis-3498225
routers:
- name: main
  routes:
  - application_name: animais-perdidos-api
    paths:
    - /*